# Generated by Django 5.0 on 2023-12-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_number', models.CharField(default=None, max_length=20)),
                ('kilometer', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('car_name', models.CharField(max_length=100)),
                ('car_year', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=50)),
                ('car_picture', models.ImageField(blank=True, null=True, upload_to='car_stock_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_image', models.ImageField(blank=True, null=True, upload_to='contract_images/')),
                ('invoice_image', models.ImageField(blank=True, default=None, null=True, upload_to='invoice_images/')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('hold_release_date', models.DateField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deposit_status', models.BooleanField(default=True)),
                ('car_exterior_image1', models.ImageField(blank=True, null=True, upload_to='car_exterior_images/')),
                ('car_exterior_image2', models.ImageField(blank=True, null=True, upload_to='car_exterior_images/')),
                ('car_exterior_image3', models.ImageField(blank=True, null=True, upload_to='car_exterior_images/')),
                ('car_exterior_image4', models.ImageField(blank=True, null=True, upload_to='car_exterior_images/')),
                ('car_exterior_image5', models.ImageField(blank=True, null=True, upload_to='car_exterior_images/')),
                ('car_interior_image1', models.ImageField(blank=True, null=True, upload_to='car_interior_images/')),
                ('car_interior_image2', models.ImageField(blank=True, null=True, upload_to='car_interior_images/')),
                ('car_interior_image3', models.ImageField(blank=True, null=True, upload_to='car_interior_images/')),
                ('car_interior_image4', models.ImageField(blank=True, null=True, upload_to='car_interior_images/')),
                ('car_interior_image5', models.ImageField(blank=True, null=True, upload_to='car_interior_images/')),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_picture', models.ImageField(blank=True, null=True, upload_to='fine_images/')),
                ('fine_number', models.CharField(default=None, max_length=50)),
                ('fine_type', models.CharField(max_length=100)),
                ('fine_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contract')),
            ],
        ),
    ]
